### ISSUE TITLE
Disconnecting causes undefined behavior

### ISSUE THREAD

**Issue by NoAvailableAlias** [santa01/signals#1]
There is an inherent flaw with your slot handles (an integer) as disconnecting a handle will invalidate any and all other handles that may or may not exist. With the current architecture you would need to "tombstone" the slot at that specific handle location instead of removing from the container. This could also be resolved by switching from a std::vector to a std::list. Instead of connect returning an integer handle return a std::list const_iterator as std::list iterators are guaranteed to never be invalidated. Then you can change the disconnect function to accept and erase a std::list const_iterator.

**Comment by santa01** [comment]
disconnect() indeed invalidates all the handles next to the deleted one, thanks for the hint.

**Comment by santa01** [comment]
Should be fine now.
